stages:
  - deploy
deploy_job:
  stage: deploy
  script:
    - |
      rsync -az -e "ssh -i ~/.ssh/runner" --exclude=".git/" --exclude=".gitlab-ci.yml" --delete ./ $webserver:$wwwpath/postnummer.xyz
      ssh -i ~/.ssh/runner $webserver "
        rm -f $wwwpath/postnummer.xyz/README.md
        rm -f $wwwpath/postnummer.xyz/LICENSE
      "